openapi: 3.0.0
info:
  title: Agent Invocation Request SQS Message Format
  description: |
    SQS メッセージ形式: SlackEventHandler から Agent Invoker への実行リクエスト
    
    SlackEventHandler Lambda は検証・認可後にこの形式で agent-invocation-request キューにメッセージを送信します。
    Agent Invoker Lambda はメッセージを受信し、InvokeAgentRuntime(Verification Agent) の payload に変換して呼び出します。
  version: 1.0.0

servers:
  - url: sqs://agent-invocation-request
    description: SQS キュー（検証スタックに配置）

paths:
  /send:
    post:
      summary: SlackEventHandler が SQS に実行リクエストを送信
      description: |
        検証・認可済みの app_mention 等について、実行リクエストをキューに投入します。
      operationId: sendAgentInvocationRequest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgentInvocationRequest'
      responses:
        '200':
          description: メッセージ送信成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  MessageId:
                    type: string
                    description: SQS メッセージ ID
        '400':
          description: リクエスト形式エラー
        '500':
          description: SQS 送信失敗（Slack が再送するため重複排除で二重実行を防ぐ）

components:
  schemas:
    AgentInvocationRequest:
      type: object
      required:
        - channel
        - text
        - thread_ts
        - team_id
        - user_id
        - event_id
      properties:
        channel:
          type: string
          description: Slack チャンネル ID
          example: "C0A6K3QRZFA"
        text:
          type: string
          description: ユーザー入力テキスト（メンション除去後）
        bot_token:
          type: [ string, "null" ]
          description: Slack Bot Token（取得できた場合）。機密のためログに出力しない
          nullable: true
        thread_ts:
          type: string
          description: スレッドタイムスタンプ
          example: "1770527263.172399"
        attachments:
          type: array
          description: Slack 添付データ
          default: []
          items: {}
        correlation_id:
          type: string
          description: トレース用相関 ID（例: Lambda request_id）
        team_id:
          type: string
          description: Slack チーム ID
        user_id:
          type: string
          description: Slack ユーザー ID
        event_id:
          type: string
          description: Slack イベント ID（重複排除・ログ紐付け用）
          example: "Ev0ADH4C7VQT"
