openapi: 3.0.0
info:
  title: Execution Response SQS Message Format
  description: |
    SQS メッセージ形式: 実行ゾーンから検証ゾーンへのレスポンス
    
    実行ゾーンは Bedrock API 呼び出し完了後、この形式で SQS キューにメッセージを送信します。
    検証ゾーンは SQS イベントソースとして Lambda 関数を設定し、メッセージを受信して Slack API に投稿します。
  version: 1.0.0
  contact:
    name: Slack AI App Team

servers:
  - url: sqs://execution-response-queue
    description: SQS キュー（検証スタックに配置）

paths:
  /send:
    post:
      summary: 実行ゾーンから SQS キューにメッセージを送信
      description: |
        Bedrock API 呼び出し完了後、実行ゾーンはこの形式で SQS キューにメッセージを送信します。
      operationId: sendExecutionResponse
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExecutionResponse'
      responses:
        '200':
          description: メッセージ送信成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  MessageId:
                    type: string
                    description: SQS メッセージ ID
                  MD5OfBody:
                    type: string
                    description: メッセージボディの MD5 ハッシュ
        '400':
          description: リクエスト形式エラー
        '403':
          description: SQS キューへのアクセス権限なし
        '500':
          description: SQS サービスエラー

components:
  schemas:
    ExecutionResponse:
      type: object
      required:
        - status
        - channel
        - bot_token
      properties:
        status:
          type: string
          enum:
            - success
            - error
          description: レスポンスステータス
          example: "success"
        channel:
          type: string
          description: Slack チャンネル ID
          example: "C01234567"
        thread_ts:
          type: string
          description: スレッドタイムスタンプ（スレッド返信の場合）
          example: "1234567890.123456"
        correlation_id:
          type: string
          format: uuid
          description: リクエスト相関 ID（トレーシング用）
          example: "550e8400-e29b-41d4-a716-446655440000"
        bot_token:
          type: string
          pattern: '^xoxb-'
          description: Slack bot OAuth トークン
          example: "xoxb-EXAMPLE-TOKEN-REPLACE-WITH-ACTUAL-TOKEN"
        response_text:
          type: string
          description: AI 生成レスポンステキスト（成功時、最大 4000 文字）
          example: "AI generated response text here..."
        error_code:
          type: string
          description: エラーコード（エラー時）
          enum:
            - bedrock_timeout
            - bedrock_throttling
            - bedrock_access_denied
            - invalid_response
            - image_processing_error
            - image_download_failed
            - document_extraction_failed
            - unsupported_file_type
            - generic
          example: "bedrock_timeout"
        error_message:
          type: string
          description: ユーザーフレンドリーなエラーメッセージ（エラー時）
          example: "Sorry, the AI service is taking longer than usual. Please try again in a moment."
      oneOf:
        - required:
            - response_text
          description: 成功時のレスポンス
        - required:
            - error_code
            - error_message
          description: エラー時のレスポンス

    SQSMessage:
      type: object
      description: SQS メッセージ形式（ExecutionResponse のラッパー）
      required:
        - MessageBody
      properties:
        MessageBody:
          type: string
          description: JSON エンコードされた ExecutionResponse
          example: '{"status":"success","channel":"C01234567","thread_ts":"1234567890.123456","correlation_id":"550e8400-e29b-41d4-a716-446655440000","bot_token":"xoxb-...","response_text":"AI response..."}'
        MessageAttributes:
          type: object
          description: メッセージ属性（オプション）
          properties:
            correlation_id:
              type: object
              properties:
                StringValue:
                  type: string
                  format: uuid
                DataType:
                  type: string
                  example: "String"

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: エラータイプ
          example: "ValidationError"
        message:
          type: string
          description: エラーメッセージ
          example: "Invalid status value. Must be 'success' or 'error'."

